export const items = [
  {
    id: Math.random(),
    title: "BreakFast",
    description: "وصف الفطار",
    price: "100 جنيه",
    category: "BreakFast",
    imgUrl: "1.png",
  },
  {
    id: Math.random(),
    title: "Lunch Food",
    description: "وصف الفطار",
    price: "80 جنيه",
    category: "Lunch Food",
    imgUrl: "2.png",
  },
  {
    id: Math.random(),
    title: "Dinner Food",
    description: "وصف الفطار",
    price: "40 جنيه",
    category: "Dinner Food",
    imgUrl: "3.png",
  },
  {
    id: Math.random(),
    title: "Lunch Food",
    description: "وصف الفطار",
    price: "30 جنيه",
    category: "Lunch Food",
    imgUrl: "2.png",
  },
  {
    id: Math.random(),
    title: "Dinner Food",
    description: "وصف الفطار",
    price: "50 جنيه",
    category: "Dinner Food",
    imgUrl: "1.png",
  },
  {
    id: Math.random(),
    title: "BreakFast",
    description: "وصف الفطار",
    price: "50 جنيه",
    category: "BreakFast",
    imgUrl: "3.png",
  },
  {
    id: Math.random(),
    title: "وجبه سناك",
    description: "وصف الفطار",
    price: "50 جنيه",
    category: "سناك",
    imgUrl: "3.png",
  },
];
